openapi: 3.0.0
info:
  title: UnaHur Anti-Social Net API
  description: API para la red social Anti-Social Net, desarrollada como parte de un trabajo práctico.
  version: 1.0.0
  contact:
    name: Semaforo En Rojo
    email: contacto@unahur.edu.ar

servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

tag:
  - name: User
    description: Usuarios
  - name: post
    description: Publicaciones
  - name: comment
    description: Comentarios
  - name: tag
    description: Etiquetas

paths:
  /user:
    get:
      summary: Obtener todos los usuarios
      tag: [User]
      responses:
        200:
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'

    post:
      summary: Crear un nuevo usuario
      tag: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /user/id:
    get:
      summary: Obtener un usuario por id
      tag: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Datos del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

    put:
      summary: Actualizar un usuario por id
      tag: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        200:
          description: Usuario actualizado

    delete:
      summary: Eliminar un usuario
      tag: [User]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Usuario eliminado

  /post:
    get:
      summary: Obtener todas las publicaciones
      tag: [post]
      responses:
        200:
          description: Lista de posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/post'

    post:
      summary: Crear un nuevo post
      tag: [post]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post'
      responses:
        201:
          description: Post creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
  /post/{id}:
    put:
      summary: Actualizar una publicacion por ID
      tag:
        - post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Publicacion actualizada exitosamente
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar una publicacion por ID
      description: Elimina una publicacion y todos sus recursos
      tag:
        - post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Publicacion eliminada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Publicacion eliminada exitosamente"
        '500':
          description: Error interno del servidor
  /post/{id}/image/{idImage}:
    delete:
      summary: Eliminar una imagen especi­fica de un post
      tag:
        - post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del post
        - name: idImage
          in: path
          required: true
          schema:
            type: integer
          description: ID de la imagen a eliminar
      responses:
        '200':
          description: Imagen eliminada exitosamente
        '500':
          description: Error al eliminar la imagen

    put:
      summary: Actualizar una publicacion con imagenes
      tag:
        - post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: Contenido actualizado del post
                imagenes:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Nuevas imagenes para agregar al post
      responses:
        '200':
          description: Publicacion actualizada exitosamente
        '500':
          description: Error al actualizar la publicacion
  /comment:
    get:
      summary: Obtener todos los comentarios
      tag:
        - comment
      responses:
        '200':
          description: Lista de comentarios
        '500':
          description: Error interno del servidor

    post:
      summary: Agregar un comentario
      tag: [comment]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comment'
      responses:
        201:
          description: Comentario agregado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
  /comment/{id}:
    put:
      summary: Actualizar un comentario por ID
      tag:
        - comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comment'
      responses:
        '201':
          description: Comentario actualizado exitosamente
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un comentario por ID
      tag:
        - comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Comentario eliminado exitosamente
        '500':
          description: Error interno del servidor
  /tag:
    get:
      summary: Obtener todas las etiquetas
      tag: [tag]
      responses:
        200:
          description: Lista de etiquetas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tag'

    post:
      summary: Crear una nueva etiqueta
      tag: [tag]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tag'
      responses:
        201:
          description: Etiqueta creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tag'
  /tag/{id}:
    put:
      summary: Actualizar una etiqueta por ID
      tag:
        - tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la etiqueta a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '201':
          description: Etiqueta actualizada exitosamente
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar una etiqueta por ID
      tag:
        - tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la etiqueta a eliminar
      responses:
        '500':
          description: Error interno del servidor
components:
  schemas:
    User:
      type: object
      required:
        - nickName
        - email
        - pasword
      properties:
        _id:
          type: string
        nickName:
          type: string
        email:
          type: string
        pasword:
          type: string
      example:
        _id: 60f5a1f99d1b2c001c8e4d3a
        nickName: "juan123"
        email: "juan@example.com"
        pasword: "60f5a1f99d"

    post:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        description:
          type: string
        image:
          type: array
          items:
            type: string
        tag:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
      example:
        _id: 60f5a1f99d1b2c001c8e4d3f
        userId: "60f5a1f99d1b2c001c8e4d3a"
        description: "Hoy fue un buen día."
        image: ["http://localhost:3000/image/img1.jpg"]
        tag: ["feliz", "sol"]
        createdAt: "2023-11-01T10:30:00Z"

    post:
      type: object
      required:
        - userId
        - description
      properties:
        userId:
          type: string
        description:
          type: string
        tag:
          type: array
          items:
            type: string
        image:
          type: array
          items:
            type: string

    comment:
      type: object
      properties:
        _id:
          type: string
        postId:
          type: string
        userId:
          type: string
        content:
          type: string
        visible:
          type: boolean
        createdAt:
          type: string
          format: date-time

    comment:
      type: object
      required:
        - postId
        - userId
        - content
      properties:
        postId:
          type: string
        userId:
          type: string
        content:
          type: string

    tag:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        post:
          type: array
          items:
            type: string

    tag:
      type: object
      required:
        - name
      properties:
        name:
          type: string